### ISSUE TITLE
problem with async.js

### ISSUE THREAD

**Issue by helio-silva** [ndrut/node-dnsbl#2]
Got this error message

iggy:node-dnsbl iggy$ node rbl.js

/Users/iggy/dev/node/node-dnsbl/rbl.js:8
    flipped = ip.split('.').reverse().join('.');
                 ^
TypeError: Cannot call method 'split' of undefined
    at flipIP (/Users/iggy/dev/node/node-dnsbl/rbl.js:8:18)
    at host (/Users/iggy/dev/node/node-dnsbl/rbl.js:21:2)
    at /Users/iggy/dev/node/node-dnsbl/node_modules/async/lib/async.js:108:13
    at Array.forEach (native)
    at _each (/Users/iggy/dev/node/node-dnsbl/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/Users/iggy/dev/node/node-dnsbl/node_modules/async/lib/async.js:107:9)
    at Object.<anonymous> (/Users/iggy/dev/node/node-dnsbl/rbl.js:12:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

thanks

**Comment by ndrut** [comment]
Sorry about that, this hasn't been updated or modified in quite some time. That particular client script has been an orphan since just after the beginning. No error handling was built into it. However, if you provide an IP address as an argument, you may get past that error.
